root = "."
tmp_dir = "tmp"

[build]
cmd = "go build -o ./bin/lightlogger ./cmd/lightlogger"
bin = "./bin/lightlogger"
full_bin = ""
include_ext = ["go", "tpl", "tmpl", "html"]
exclude_dir = ["vendor", "tmp", "bin", ".git", "node_modules"]
exclude_file = []
exclude_regex = ["_test.go$"]
exclude_unchanged = false
follow_symlink = false
delay = 1000
stop_on_root = false
send_interrupt = false
kill_delay = 0

[color]
main = "magenta"
watcher = "cyan"
build = "yellow"
runner = "green"

[misc]
clean_on_exit = false

[log]
time = true

[proxy]
enabled = false
proxy_port = 8090
app_port = 8080
