root = "."
tmp_dir = "tmp"

[build]
cmd = "go build -o ./bin/lightlogger ./cmd/lightlogger"
bin = "./bin/lightlogger"
full_bin = ""
include_ext = ["go"]
exclude_dir = ["vendor", "tmp", "bin", ".git"]
exclude_regex = ["_test.go$"]
delay = 1000

[log]
time = true
